services:
  # A Docker web service
  - type: web
    name: notes-app
    runtime: python
    plan: starter
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT